name: Test Preprocessing !!INCOMPLETE!!

on: [push]

jobs:
  test-addition:
    uses: ./.github/workflows/run_pytest.yaml
    with:
      file: test_preprocessing.py
      testname: Test Preprocessing